### ISSUE TITLE
Layout

### ISSUE THREAD

**Issue by JoseskVolpe** [faissaloo/telegram-micro#4]
I'm making something that i think it might help with the project's layout in the future
https://github.com/JoseskVolpe/PixelyVulpine-Layout

**Comment by JoseskVolpe** [comment]
Also, ¿could you open Discussion? ^w^"

I think it's much better to discuss about stuff that aren't really suggestions or bug reports, like this one

**Comment by faissaloo** [comment]
Just saw this lol, looks interesting I'll consider it as long as it's not too big but I've gotten busy with life stuff atm so it might be a while before I get back to this project

**Comment by JoseskVolpe** [comment]
Alright :3
I am busy these times too lol Butbi will return the work on it
Its currently a little over 100kb, but i will do some optimizations soon that will reduce it size once alpha be released
