### ISSUE TITLE
This is not an issue but probably helps you.

### ISSUE THREAD

**Issue by Varo95** [faissaloo/telegram-micro#5]
https://vikamobile.ru/ Stella Mobile is a j2me app(Telegram client), hope that this can help you with something. I'm an starter developer too, but hope that your proyect come outs and shine, i really love j2me old phones, they take me back to the childhood

**Comment by faissaloo** [comment]
Thanks for this and I appreciate the words, do you know if there's any source code for that app anywhere?

**Comment by Varo95** [comment]
I decoded it with my Intellij. I will upload the folder system as compiled one(as a zip). I will post another comment here to do that, just give me a sec.

**Comment by Varo95** [comment]
Hope that this can help u. I try to setup a j2me development environment but with no success.
[StellaMobile-5-Decompiled.zip](https://github.com/faissaloo/telegram-micro/files/7590528/StellaMobile-5-Decompiled.zip)

**Comment by shinovon** [comment]
Stella Mobile is server-side application

**Comment by faissaloo** [comment]
@shinovon You mean it doesn't directly use MTProto on the phone?

**Comment by shinovon** [comment]
> @shinovon You mean it doesn't directly use MTProto on the phone?

Yes

**Comment by faissaloo** [comment]
Aight, in that case it's not mega useful to me, since this project is for an MTProto implementation on the device

**Comment by JoseskVolpe** [comment]
Stella Mobile is closed-source aswell

**Comment by santi100a** [comment]
It'd be nice to have a J2ME client for Stella Mobile so I don't have to use the browser.
